# Vipunen Project Configuration

# Column mappings for input and output
columns:
  input:
    year: 'tilastovuosi'
    degree_type: 'tutkintotyyppi'
    qualification: 'tutkinto' 
    provider: 'koulutuksenJarjestaja'
    subcontractor: 'hankintakoulutuksenJarjestaja'
    volume: 'nettoopiskelijamaaraLkm'
    update_date: 'tietojoukkoPaivitettyPvm'
  
  output:
    year: 'Year'
    qualification: 'Qualification'
    provider: 'Provider'
    provider_amount: 'Provider Amount'
    subcontractor_amount: 'Subcontractor Amount'
    total_volume: 'Total Volume'
    market_total: 'Market Total'
    market_share: 'Market Share (%)'
    market_rank: 'Market Rank'
    market_share_growth: 'Market Share Growth (%)'
    market_gainer: 'market gainer'

# Institution information
# Change as needed to match the institution you want to analyze
institutions:
  default:
    name: "Rastor-instituutti ry"
    short_name: "RI"
    variants:
      - "RASTOR OY"
      - "Rastor Oy"

# Qualification types to filter
qualification_types:
  - "Ammattitutkinnot"
  - "Erikoisammattitutkinnot"
  - "Ammatilliset perustutkinnot"

# File paths
paths:
  data: "data/raw/amm_opiskelijat_ja_tutkinnot_vuosi_tutkinto.csv"
  output: "data/reports"

# API Configuration
api:
  base_url: "https://api.vipunen.fi/api/resources"
  default_dataset: "amm_opiskelijat_ja_tutkinnot_vuosi_tutkinto"
  limit: 5000
  max_retries: 3
  retry_delay: 5 # seconds
  timeout: 60 # seconds increased timeout
  caller_id: "0201689-0.rastor-instituutti" # TODO: Consider moving to environment variable
  backup_dir_name: "old_api_calls_output"
  csv_separator: ";"
  csv_encoding: "utf-8"
  metadata_dir_name: ".metadata" # Directory for storing update date info

# Excel export settings
excel:
  sheets:
    - name: "Total Volumes"
      description: "Total student volumes by year"
    - name: "Volumes by Qualification"
      description: "Student volumes broken down by qualification"
    - name: "Provider's Market"
      description: "Market analysis including all providers"
    - name: "CAGR Analysis"
      description: "Compound Annual Growth Rate analysis"

# Analysis configurations
analysis:
  # Minimum total market size for a qualification in the reference year to be included in the overall analysis.
  # This helps filter out very small or niche qualifications from detailed reports.
  min_market_size_threshold: 5 
  
  # Minimum summed volume the institution must have across the last two full years 
  # for a qualification to be considered 'active' for visualization filtering.
  # Set to 1 to include any qualification with any volume in the last two years.
  # Set to 3 to require volume > 2 summed across the two years.
  active_qualification_min_volume_sum: 3 # Default: 3 Requires summed volume > 2
  
  # Configuration for the 'Gainers and Losers' visualization
  gainers_losers:
    # Minimum market share (%) a provider must have in the reference year to be considered
    # for the gainers/losers plot. Set to null or remove to disable.
    # Example: 0.5 means only providers with >= 0.5% market share are included.
    # min_market_share_threshold: null # Default: no threshold
    min_market_share_threshold: 0.5 # Default: no threshold
    
    # Minimum market rank percentile a provider must be in (based on market share in the reference year)
    # to be considered for the gainers/losers plot. Set to null or remove to disable.
    # Example: 90 means only providers in the top 10% (ranks 1, 2, 3...) are included.
    # Lower rank numbers are better (Rank 1 is the highest market share).
    min_market_rank_percentile: null # Default: no threshold 